# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'demo110' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for demo110
pod 'NIMSDK'
end

#target 'son' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!
#
#  # Pods for son
#
#end
#
#target 'sonSetupUI' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   use_frameworks!
#
#  # Pods for sonSetupUI
#
#end
